schema_version: 1

context:
  version: "18.7.0"
  python_min: "3.11"

package:
  name: ltex-ls
  version: ${{ version }}

source:
  url: https://github.com/ltex-plus/ltex-ls-plus/archive/refs/tags/${{ version }}.tar.gz
  sha256: 8c5ad69fdbf38061bc511439473b081f2b2db35b0f4788f3516c632345788d2f

build:
  number: 0
  noarch: generic

requirements:
  host:
    - maven
    - openjdk
    - python =${{ python_min }}
    - sed
  run:
    - openjdk
    - python >=${{ python_min }}

tests:
  - script:
      - ltex-ls --help
      - ltex-cli --help
      - ltex-ls-plus --help
      - ltex-cli-plus --help

about:
  license: MPL-2.0
  license_file:
    - LICENSE.md
    - target/generated-resources/licenses/
  summary: LSP language server for LanguageTool with support for LaTeX, Markdown, and others
  homepage: https://github.com/valentjn/ltex-ls

extra:
  recipe-maintainers:
    - danielnachun
